version: '3.1'
services:
    nginx:
        image: nginx
        container_name: nginx
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
        - "80:80"
        environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80
    tomcat1:
        image: tomcat:8.5.43
        container_name: tomcat1
    tomcat2:
        image: tomcat:8.5.43
        container_name: tomcat2
